name: tcg_postgres_service

services:
  postgres:
    image: postgres:16-alpine
    container_name: tcg_postgres
    restart: no
    env_file:
      - .env
    environment:
      POSTGRES_USER: tcg_user
      POSTGRES_PASSWORD: tcg_password
      POSTGRES_DB: tcg_database
    ports:
      - '5433:5432'
    volumes:
      - .cache/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U tcg_user -d tcg_database']
      interval: 10s
      timeout: 5s
      retries: 5
